/* tslint:disable */
/* eslint-disable */
/**
 * This file was auto-generated by Payload.
 * DO NOT MODIFY IT MANUALLY. Instead, run `npx payload generate:types` to regenerate.
 * Manual edits will be overwritten on next type generation.
 */

export interface Config {
  collections: {
    users: User
    brands: Brand
    devices: Device
    articles: Article
    media: Media
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  globals: {}
}

export interface User {
  id: string
  role?: 'admin' | 'editor' | 'viewer' | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}

export interface Brand {
  id: string
  name: string
  slug: string
  logo?: string | null
  website?: string | null
  featured?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface Device {
  id: string
  name: string
  slug: string
  brand: string | Brand
  releaseYear: number
  category: 'flagship' | 'mid-range' | 'budget' | 'ultra-premium'
  priceKES?: number | null
  priceUSD?: number | null
  tagline?: string | null
  status: 'draft' | 'published'
  images?:
    | {
        url: string
        alt: string
        colour?: string | null
        isPrimary?: boolean | null
        id?: string | null
      }[]
    | null
  scores: {
    display: number
    performance: number
    camera: number
    battery: number
    value: number
    overall?: number | null
  }
  verdict?: {
    pros?:
      | {
          point: string
          id?: string | null
        }[]
      | null
    cons?:
      | {
          point: string
          id?: string | null
        }[]
      | null
    bottomLine?: string | null
    fullVerdict?: Record<string, unknown> | null
  } | null
  specsDesign?: {
    dimensions?: string | null
    weight?: string | null
    build?: string | null
    colours?: string | null
    waterResistance?: string | null
  } | null
  specsDisplay?: {
    size?: string | null
    type?: string | null
    resolution?: string | null
    refreshRate?: string | null
    brightness?: string | null
    protection?: string | null
  } | null
  specsProcessor?: {
    chipset?: string | null
    cpu?: string | null
    gpu?: string | null
    process?: string | null
  } | null
  specsMemory?: {
    ram?: string | null
    storage?: string | null
    expandable?: boolean | null
  } | null
  specsCamera?: {
    mainCamera?: string | null
    ultrawide?: string | null
    telephoto?: string | null
    videoMain?: string | null
    frontCamera?: string | null
    videoFront?: string | null
  } | null
  specsBattery?: {
    capacity?: string | null
    wiredCharging?: string | null
    wirelessCharging?: string | null
    reverseCharging?: string | null
  } | null
  specsConnectivity?: {
    network?: string | null
    wifi?: string | null
    bluetooth?: string | null
    nfc?: boolean | null
    usb?: string | null
    satellite?: string | null
  } | null
  specsSoftware?: {
    os?: string | null
    ui?: string | null
    updatePolicy?: string | null
  } | null
  benchmarks?: {
    geekbenchSingle?: number | null
    geekbenchMulti?: number | null
    antutu?: number | null
    pcmark?: number | null
  } | null
  buyLinks?:
    | {
        retailer: 'jumia' | 'amazon' | 'kilimall' | 'carrier' | 'other'
        url: string
        price?: string | null
        priceDate?: string | null
        id?: string | null
      }[]
    | null
  relatedVideo?: string | null
  relatedTiktok?: string | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    ogImageUrl?: string | null
  } | null
  updatedAt: string
  createdAt: string
}

export interface Article {
  id: string
  title: string
  slug: string
  status: 'draft' | 'published'
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}

export interface PayloadPreference {
  id: string
  user: string | User
  key?: string | null
  value?:
    | Record<string, unknown>
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}

export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}